accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/block", views.block, name="block"),
    path("block_user/", views.block_user, name="block_user"),
    path("<int:pk>/block_user_block", views.block_user_block, name="block_user_block"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("main/", views.main, name="main"),
    path("board/", views.board, name="board"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),

    path("<int:pk>/delete_participate/", views.delete_participate, name="delete_participate"),

    path("<int:pk>/comment/", views.comment, name="comment"),
    path(
        "<int:pk>/comment_delete/<int:comment_pk>",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:pk>/comment_update/<int:comment_pk>",
        views.comment_update,
        name="comment_update",
    ),
    path("<int:pk>/participate/", views.participate, name="participate"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("support/", views.support, name="support"),
]

maps/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("map/", views.map, name="map"),
    path("map/<str:x>/<str:y>/", views.map_search, name="map_search"),
    path("map/search/<str:x>/<str:y>/", views.search, name="search"),
]

sanmepjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("map/", include("maps.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from decimal import Decimal
from django import forms
from multiselectfield import MultiSelectField
from django.utils import timezone

# Create your models here.


class User(AbstractUser):
    nickname = models.CharField(max_length=10)  # 별명
    MBTI_CHOICES = (
        ("ISTJ", "ISTJ"),
        ("ISTP", "ISTP"),
        ("ISFJ", "ISFJ"),
        ("ISFP", "ISFP"),
        ("INTJ", "INTJ"),
        ("INTP", "INTP"),
        ("INFJ", "INFJ"),
        ("INFP", "INFP"),
        ("ESTJ", "ESTJ"),
        ("ESTP", "ESTP"),
        ("ESFJ", "ESFJ"),
        ("ESFP", "ESFP"),
        ("ENTJ", "ENTJ"),
        ("ENTP", "ENTP"),
        ("ENFJ", "ENFJ"),
        ("ENFP", "ENFP"),
    )

    mbti = models.CharField(
        max_length=10,
        choices=MBTI_CHOICES,
    )  # mbti
    address = models.CharField(max_length=50)  # 주소
    address_detail = models.CharField(max_length=40, null=True)  # 상세주소
    birth = models.DateTimeField(default=timezone.now)  # 나이
    GENDER_CHOICES = (
        ("M", "남자"),
        ("F", "여자"),
    )
    gender = models.CharField(  # 성별
        max_length=2,
        choices=GENDER_CHOICES,
    )

    MANNER_CHOICES = (
        ("활발", "활발한"),
        ("조용", "조용한"),
        ("애교", "애교가 넘치는"),
        ("어른", "어른스러운"),
        ("열정", "열정적인"),
        ("침착", "침착한"),
        ("예의", "예의바른"),
        ("유머", "유머러스한"),
        ("진지", "진지한"),
        ("지적", "지적인"),
        ("성실", "성실한"),
        ("감성", "감성적인"),
        ("꼼꼼", "꼼꼼한"),
        ("논리", "논리적인"),
        ("즉흥", "즉흥적인"),
        ("소심", "소심한"),
        ("쿨", "쿨한"),
    )

    manner = MultiSelectField(  # 매너(성향)
        max_length=100,
        choices=MANNER_CHOICES,
    )

    SMOKING_CHOICES = (
        ("비흡연", "비흡연"),
        ("술마실때만", "술 마실 때만"),
        ("가끔", "가끔"),
        ("매일", "매일"),
        ("아이코스", "아이코스"),
        ("전자담배", "전자담배"),
    )

    smoking = models.CharField(  # 흡연여부
        max_length=10,
        choices=SMOKING_CHOICES,
    )

    pet = models.BooleanField(default=False)  # 반려동물 유무
    agree = models.BooleanField(default=False)  # 약관내용

    profile_pic = ProcessedImageField(  # 프로필사진
        upload_to="profile/%Y%m%d/",
        # default="../static/images/profile_default.png",
        null=True,
        processors=[ResizeToFill(360, 360)],
        format="JPEG",
        options={"quality": 80},
    )
    manner_point = models.FloatField(default=36.5)  # 매너점수
    followings = models.ManyToManyField(  # 팔로워
        "self", symmetrical=False, related_name="followers"
    )
    blocking = models.ManyToManyField(
        "self", symmetrical=False, related_name="blockers"
    )

    @property
    def get_photo_url(self):

        if self.profile_pic:
            return self.profile_pic.url
        return None

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from maps.models import Map
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    day = models.DateTimeField()
    time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_post"
    )
    park_address = models.ForeignKey(Map, on_delete=models.CASCADE)
    pet = models.BooleanField(default=False)
    content = models.TextField()
    TIME_CHOICES = (
        ("00:00", "00:00"),
        ("01:00", "01:00"),
        ("02:00", "02:00"),
        ("03:00", "03:00"),
        ("04:00", "04:00"),
        ("05:00", "05:00"),
        ("06:00", "06:00"),
        ("07:00", "07:00"),
        ("08:00", "08:00"),
        ("09:00", "09:00"),
        ("10:00", "10:00"),
        ("11:00", "11:00"),
        ("12:00", "12:00"),
        ("13:00", "13:00"),
        ("14:00", "14:00"),
        ("15:00", "15:00"),
        ("16:00", "16:00"),
        ("17:00", "17:00"),
        ("18:00", "18:00"),
        ("19:00", "19:00"),
        ("20:00", "20:00"),
        ("21:00", "21:00"),
        ("22:00", "22:00"),
        ("23:00", "23:00"),
        ("24:00", "24:00"),
    )
    time = models.CharField(max_length=20, choices=TIME_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    participate_people = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    participate = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="participater"
    )
    hit = models.PositiveBigIntegerField(default=0)

    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )

    @property
    def update_conter(self):
        self.hit = self.hit + 1
        self.save()


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Search(models.Model):
    title = models.CharField(max_length=10)
    count = models.PositiveIntegerField(default=0)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model


class DateInput(forms.DateInput):
    input_type = "Date"


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "profile_pic",
            "username",
            "email",
            "nickname",
            "mbti",
            "birth",
            "address",
            "address_detail",
            "gender",
            "manner",
            "smoking",
            "pet",
            "agree",
        )
        widgets = {
            "birth": DateInput(),
        }


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "profile_pic",
            "username",
            "email",
            "nickname",
            "mbti",
            "birth",
            "address",
            "address_detail",
            "gender",
            "manner",
            "smoking",
            "pet",
        )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_safe
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from .forms import CustomUserChangeForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import JsonResponse

# Create your views here.


@require_safe
def login(request):
    if request.user.is_anonymous:
        if request.method == "POST":
            login_form = AuthenticationForm(request, data=request.POST)
            if login_form.is_valid():
                auth_login(request, login_form.get_user())

                return redirect(request.GET.get("next") or "articles:main")

        else:
            login_form = AuthenticationForm()

        context = {
            "login_form": login_form,
        }
        return render(request, "accounts/login.html", context)
    else:
        return HttpResponseRedirect("/")


@login_required
def logout(request):
    auth_logout(request)
    return redirect("accounts:login")


def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()  # ModelForm의 save메소드의 리턴값은 해당 모델의 인스턴스다
            auth_login(request, user)  # 로그인
            return redirect("articles:main")
    else:
        form = CustomUserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "accounts/signup.html", context)


@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        "user": user,
    }
    return render(request, "accounts/detail.html", context)


@login_required
def update(request, pk):
    user_info = get_user_model().objects.get(pk=pk)
    # 요청한 유저가 로그인한 해당 유저인 경우
    if request.method == "POST":
        user_form = CustomUserChangeForm(
            request.POST, request.FILES, instance=request.user
        )
        # 유저폼 유효성 확인
        if user_form.is_valid():
            user_form.save()
            return redirect("accounts:detail", user_info.pk)
    else:
        user_form = CustomUserChangeForm(instance=request.user)
    context = {"user_form": user_form}
    return render(request, "accounts/update.html", context)


# def follow(request, pk):
#     accounts = get_user_model().objects.get(pk=pk)
#     if request.user == accounts:
#         return redirect("accounts:detail", pk)
#     if request.user in accounts.followers.all():
#         accounts.followers.remove(request.user)
#     else:
#         accounts.followers.add(request.user)
#     return redirect("accounts:detail", pk)


# 팔로우
# @login_required
# def follow(request, pk):
#     if request.user.is_authenticated:
#         User = get_user_model()
#         me = request.user
#         you = User.objects.get(pk=pk)
#         if me != you:
#             if you.followers.filter(pk=me.pk).exists():
#                 you.followers.remove(me)
#                 you.manner -= 0.2
#                 you.save()
#                 is_followed = False
#             else:
#                 you.followers.add(me)
#                 you.manner += 0.2
#                 you.save()
#                 is_followed = True
#             context = {
#                 "is_followed": is_followed,
#                 "followers_count": you.followers.count(),
#                 "followings_count": you.followings.count(),
#             }
#             return JsonResponse(context)
#         return redirect("accounts:detail", you.username)
#     return redirect("accounts:login")


@login_required
def follow(request, pk):
    accounts = get_user_model().objects.get(pk=pk)
    if request.user == accounts:
        return redirect("accounts:detail", pk)
    if request.user in accounts.followers.all():
        accounts.followers.remove(request.user)
        accounts.manner_point -= 0.2
        accounts.manner_point = round(accounts.manner_point, 1)
        accounts.save()
    else:
        accounts.followers.add(request.user)
        accounts.manner_point += 0.2
        accounts.manner_point = round(accounts.manner_point, 1)
        accounts.save()
    # 상세 페이지로 redirect
    return redirect("accounts:detail", pk)


@login_required
def block(request, pk):
    user = get_user_model().objects.get(pk=pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.manner_point += 1
            user.manner_point = round(user.manner_point, 1)
            user.save()
        else:
            user.blockers.add(request.user)
            user.manner_point -= 1
            user.manner_point = round(user.manner_point, 1)
            user.save()
    return redirect("accounts:detail", pk)


@login_required
def block_user(request):
    blockers = request.user.blocking.all()
    context = {
        "blockers": blockers,
    }
    return render(request, "accounts/block_user.html", context)


@login_required
def block_user_block(request, pk):
    user = get_user_model().objects.get(pk=pk)
    if user != request.user:
        if user.blockers.filter(pk=request.user.pk).exists():
            user.blockers.remove(request.user)
            user.manner_point += 1
            user.save()
        else:
            user.blockers.add(request.user)
            user.manner_point -= 1
            user.save()
    return redirect("accounts:block_user")


@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("articles:index")

accounts/templates/accounts/block_user.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
<section class="home"></section>
{% if user.blockers %}
{% for block_user in blockers %}
<div class="card m-4 p-2">
    <div class="d-flex justify-content-center">
        <img src="{{block_user.profile_pic.url}}" class="rounded-circle" alt="" style="height: 50px; width:50px;">
        <p class="align-self-center pt-3 ms-4">
            {{ block_user.username }}</a>
        </p>
        <a class="ms-5 align-self-center text-decoration-none text-black fw-bold"
            href="{% url 'accounts:block_user_block' block_user.pk %}">차단 취소</a>
    </div>
</div>
{% endfor %}
{% endif %}

{% endblock content %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}

{% block title %}
  |
  {{ user.nickname }}님의 프로필{% endblock title %}

{% block content %}
  <!-- 팔로워 모달 -->
  <div class="modal fade title-font" id="followerModal" tabindex="-1" aria-labelledby="followerModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title w-100 text-center fw-bold" id="followerModalLabel">Followers</h5>
        </div>
        <div class="modal-body">
          {% if user.followers.all %}
            {% for follower in user.followers.all %}
              <a href="{% url 'accounts:detail' follower.pk %}" class="modal-participater" style="color: black; text-decoration: none;">
                <div class="d-flex align-items-center">
                  <!-- 프로필 이미지가 있으면 -->
                  <img src="{{ follower.profile_pic.url }}">
                  <!-- 이름이 있으면 이름, 없으면 아이디 -->
                  <h1>{{ follower.username }}</h1>
                </div>
              </a>
            {% endfor %}
          {% else %}
            <div class="text-center">팔로워가 없습니다.</div>
          {% endif %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn pos-btn" data-bs-dismiss="modal">닫기</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 팔로잉 모달 -->
  <div class="modal fade title-font" id="followingModal" tabindex="-1" aria-labelledby="followingModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title w-100 text-center" id="followingModalLabel">Followings</h5>
        </div>
        <div class="modal-body">
          {% if user.followings.all %}
            {% for following in user.followings.all %}
              <a href="{% url 'accounts:detail' following.pk %}" class="modal-participater" style="color: black; text-decoration: none;">
                <div class="d-flex align-items-center">
                  <img src="{{ following.profile_pic.url }}">
                  <!-- 이름이 있으면 이름, 없으면 아이디 -->
                  <h1>{{ following.username }}</h1>
                </div>
              </a>
            {% endfor %}
          {% else %}
            <div class="text-center">팔로우 중인 사람이 없습니다.</div>
          {% endif %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn pos-btn" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 프로필 -->
  <section class="home">
    <div class="container">
      <div class="content">
        <div height="100px"></div>
        <div class="pf-box">
          <div class="rounded-circle bg-white" style="width:300px; height:300px; background-image:url({{ user.get_photo_url }}); background-repeat:no-repeat; background-position:center; background-size:contain;"></div>
          <!--프사 옆-->
          <div class="pf-right">
            <div class="pf-detail">
              <h3 class="display-7 fw-bolder">{{ user }}</h3>
              <p class="small mb-1 lh-lg">
                닉네임 :
                {{user.nickname}}<br>
                사는 지역 :
                {{user.address}}&nbsp{{user.address_detail}}<br>
                MBTI :
                {{user.mbti}}<br>
                매너 온도 :
                {{user.manner_point}}℃
                {% if user.manner_point < 36.5 %}
                  <i>🥵</i>
                {% elif user.manner_point == 36.5 %}🙂
                {% else %}
                  😍
                {% endif %}
              </p>
              <div id="article-profile">
                <div id="article-profile-right">
                  <div class="meters">
                    {% if user.manner_point < 36.5 %}
                      <div class="bar bar-color-02" style="width:41%;"></div>
                    {% elif user.manner_point == 36.5 %}
                      <div class="bar bar-color-03" style="width:41%;"></div>
                    {% else %}
                      <div class="bar bar-color-04" style="width:41%;"></div>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
            <!-- 팔로워 표시 -->
            <div class="counts">
              <div class="me-5">
                <p class="fs-6">게시물<span class="ms-2 fw-bold">{{ user.post_set.count }}</span></p>
              </div>
              <div class="me-5">
                <p class="fs-6" data-bs-target="#followerModal" data-bs-toggle="modal">
                  팔로워
                  <span class="ms-2 fw-bold" id="followers-count">
                    {{ user.followers.count }}
                  </span>
                </p>
              </div>
              <div class="me-5">
                <p class="fs-6">팔로우<span class="ms-2 fw-bold" id="followings-count">{{ user.followings.count }}</span>
                </p>
              </div>
            </div>
            <div class="pf-btns">
              {% if request.user != user %}
                <a href="{% url 'accounts:follow' user.pk %}">
                  {% if request.user in user.followers.all %}
                    <button type="button" class="btn btn-danger">팔로우 취소</button>
                  {% else %}
                    <button type="button" class="btn btn-primary">팔로우</button>
                  {% endif %}
                </a>
              {% endif %}
              <!-- 차단 버튼 -->
              {% if request.user != user %}
                <a href="{% url 'accounts:block' user.pk %}">
                  {% if request.user in user.blockers.all %}
                    <button type="button" class="btn btn-danger">차단 취소</button>
                  {% else %}
                    <button type="button" class="btn btn-primary">차단</button>
                  {% endif %}
                </a>
              {% endif %}
              <!-- 팔로우 버튼(비동기) -->
              <!-- {% if request.user != user %} <form id='follow-form' data-user-id='{{ user.pk }}'> {% csrf_token %} {% if request.user in user.followers.all %} <input type='submit' class="neg-btn" value="언팔로우"> {% else %} <input type='submit' class="pos-btn" value='팔로우'> {% endif %} </form> {% endif %} -->

              <!-- 수정 및 삭제 -->
              {% if request.user == user %}
                <a href="{% url 'accounts:update' user.pk %}" type="button" class="btn pos-btn me-2">수정</a>
                <button type="button" class="btn neg-btn me-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                  회원탈퇴
                </button>
                <a href="{% url 'accounts:block_user' %}" class="btn awf-btn">차단 목록</a>
                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="staticBackdropLabel">회원탈퇴</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        정말 탈퇴하시겠습니까?
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'accounts:delete' %}" type="button" class="btn neg-btn">탈퇴</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- <a href="{% url 'accounts:delete' %}" type="button" class="btn neg-btn">회원탈퇴</a> -->
              {% endif %}
            </div>
          </div>
        </div>
        <!--content-->
        <div class="pf-history">
          <div class="written-p">
            <h3>작성한 글</h3>
            <p class="text-muted">{{ user.post_set.count }}개를 작성하였습니다.</p>
            <table class="table">
              <thead>
                <tr class="thead-dark">
                  <th>#</th>
                  <th>글 제목</th>
                </tr>
              </thead>
              <tbody>
                {% for article in user.post_set.all %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>
                      <a href="{% url 'articles:detail' article.pk %}">{{article.title}}</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="written-c">
            <h3>작성한 댓글</h3>
            <p class="text-muted">{{ user.comment_set.count }}개를 작성하였습니다.</p>
            <table class="table">
              <thead>
                <tr class="thead-dark">
                  <th>#</th>
                  <th>댓글 내용</th>
                </tr>
              </thead>
              <tbody>
                {% for comment in user.comment_set.all %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>
                      <a href="{% url 'articles:detail' comment.article_id %}">{{comment.content}}</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!--written-c-->
          <div class="liked">
            <h3>좋아요 누른 글</h3>
            <p class="text-muted">
              {% if user.like_articles %}{{ user.like_articles.count }}
              {% else %}0
              {% endif %}개의 글에 좋아요를 표시하였습니다.</p>
            <table class="table">
              <thead>
                <tr class="thead-dark">
                  <th>#</th>
                  <th>좋아요 표시한 글</th>
                </tr>
              </thead>
              <tbody>
                {% for article in user.like_articles.all %}
                  <tr>
                    <td>{{ forloop.counter}}</td>
                    <td>
                      <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <!--liked-->
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

{% block script %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script>
    const form = document.querySelector('#follow-form')
    const csrftoken = document
      .querySelector('[name=csrfmiddlewaretoken]')
      .value
      form
      .addEventListener('submit', function (event) {
        event.preventDefault()

        const userId = event
          .target
          .dataset
          .userId
          axios({
            method: 'post',
            url: `/accounts/${userId}/follow/`,
            headers: {
              'X-CSRFToken': csrftoken
            }
          })
          .then((response) => {
            console.log(response)
            const followersCountTag = document.querySelector('#followers-count')
            const followingsCountTag = document.querySelector('#followings-count')
            const followersCount = response.data.followers_count
            const followingsCount = response.data.followings_count
            followersCountTag.innerText = followersCount
            followingsCountTag.innerText = followingsCount
            const isFollowed = response.data.is_followed
            const followBtn = document.querySelector('#follow-form > input[type=submit]')
            if (isFollowed == true) {
              followBtn.value = '언팔로우'
            } else {
              followBtn.value = '팔로우'
            }
          })
      })
  </script>
{% endblock script %}

accounts/templates/accounts/signupzzin.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %}{% endblock title %}

{% block content %}
  <section class="home"></section>
  <div style="height: 1000px">
    <div class="content">
      <h2>회원가입</h2>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn pos-btn" content="회원가입">
      </form>
    </div>
  </div>
{% endblock content %}
{% block script %}{% endblock script %}