accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/block", views.block, name="block"),
    path("block_user/", views.block_user, name="block_user"),
    path("<int:pk>/block_user_block", views.block_user_block, name="block_user_block"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("main/", views.main, name="main"),
    path("board/", views.board, name="board"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),

    path("<int:pk>/delete_participate/", views.delete_participate, name="delete_participate"),

    path("<int:pk>/comment/", views.comment, name="comment"),
    path(
        "<int:pk>/comment_delete/<int:comment_pk>",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:pk>/comment_update/<int:comment_pk>",
        views.comment_update,
        name="comment_update",
    ),
    path("<int:pk>/participate/", views.participate, name="participate"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("support/", views.support, name="support"),
]

maps/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("map/", views.map, name="map"),
    path("map/<str:x>/<str:y>/", views.map_search, name="map_search"),
    path("map/search/<str:x>/<str:y>/", views.search, name="search"),
]

sanmepjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("map/", include("maps.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.db import models
from maps.models import Map
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    day = models.DateTimeField()
    time = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like_user = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="like_post"
    )
    park_address = models.ForeignKey(Map, on_delete=models.CASCADE)
    pet = models.BooleanField(default=False)
    content = models.TextField()
    TIME_CHOICES = (
        ("00:00", "00:00"),
        ("01:00", "01:00"),
        ("02:00", "02:00"),
        ("03:00", "03:00"),
        ("04:00", "04:00"),
        ("05:00", "05:00"),
        ("06:00", "06:00"),
        ("07:00", "07:00"),
        ("08:00", "08:00"),
        ("09:00", "09:00"),
        ("10:00", "10:00"),
        ("11:00", "11:00"),
        ("12:00", "12:00"),
        ("13:00", "13:00"),
        ("14:00", "14:00"),
        ("15:00", "15:00"),
        ("16:00", "16:00"),
        ("17:00", "17:00"),
        ("18:00", "18:00"),
        ("19:00", "19:00"),
        ("20:00", "20:00"),
        ("21:00", "21:00"),
        ("22:00", "22:00"),
        ("23:00", "23:00"),
        ("24:00", "24:00"),
    )
    time = models.CharField(max_length=20, choices=TIME_CHOICES)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    participate_people = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)]
    )
    participate = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="participater"
    )
    hit = models.PositiveBigIntegerField(default=0)

    thumbnail = ProcessedImageField(
        upload_to="images/",
        blank=True,
        processors=[ResizeToFill(1200, 960)],
        format="JPEG",
        options={"quality": 80},
    )

    @property
    def update_conter(self):
        self.hit = self.hit + 1
        self.save()


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)


class Search(models.Model):
    title = models.CharField(max_length=10)
    count = models.PositiveIntegerField(default=0)

articles/forms.py
from django import forms
from .models import Post, Comment


class DateInput(forms.DateInput):
    input_type = "date"


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "title",
            "day",
            "time",
            "pet",
            "participate_people",
            "thumbnail",
            "content",
        ]
        widgets = {
            "day": DateInput(),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_safe
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from accounts.models import User
from maps.models import Map
from .models import Post, Comment, Search
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
import json
import random

# Create your views here.
@require_safe
def index(request):
    return render(request, "articles/index.html")


@login_required
def main(request):
    mbti_info = {
        "ENTJ": ["ISFP", "INFP", "ESFP", "ESTP"],
        "ENTP": ["ISFJ", "ISTJ", "ENTP", "ESTJ"],
        "INTJ": ["ESFP", "ESTP", "ISFP", "INTP"],
        "INTP": ["ESFP", "ESTP", "ISFP", "INFP"],
        "ESTJ": ["INFP", "ISFP", "INTP", "ENTP"],
        "ESFJ": ["INTP", "ISTP", "ENTP", "ENFP"],
        "ISTJ": ["ENFP", "ENTP", "ISFP", "INFP"],
        "ISFJ": ["ENTP", "ENFP", "INTP", "ISTP"],
        "ENFJ": ["ISTP", "INTP", "ESTP", "ESFP"],
        "ENFP": ["ISTJ", "ISTJ", "ESFJ", "ESTJ"],
        "INFJ": ["ESTP", "ESFP", "ISTP", "INTP"],
        "INFP": ["ESTJ", "ENTJ", "INTJ", "ISTJ"],
        "ESTP": ["INFJ", "INTJ", "ENFJ", "ENTJ"],
        "ESFP": ["INTJ", "INFJ", "ENTJ", "ENFJ"],
        "ISTP": ["ENFJ", "ESFJ", "INFJ", "ISFJ"],
        "ISFP": ["ENTJ", "ESTJ", "INTJ", "ISTJ"],
    }
    # mbti에 따른 유저 3명 추출하기
    # 유저 정보를 가져옴
    my_data = User.objects.get(pk=request.user.pk)
    # 유저의 mbti
    my_mbti = my_data.mbti
    # 해당 유저와 잘 맞는 유저 리스트
    matched_user = []
    # mbti 키, 값
    try:
        for mbti_key, mbti_value in mbti_info.items():
            # 유저의 mbti가 키에 있으면
            if my_mbti == mbti_key:
                # 값에 해당하는 유저를 골라냄
                for info in mbti_value:
                    user_data = User.objects.filter(mbti=info)
                    # 유저 데이터가 하나의 mbti에 2개 이상일 경우
                    if len(user_data) <= 2:
                        # 1개만 랜덤으로 추려냄
                        user_data = random.choice(user_data)
                    matched_user.append(user_data)
        # 결과적으로 3개의 유저 데이터 도출
        matched_user = random.sample(matched_user, 3)
    except IndexError:
        print("해당하는 유저가 없습니다")
    except ValueError:
        print("데이터가 없습니다.")

    # 매너유저 3명
    hot_user = User.objects.all().order_by("-manner_point")[:3]
    posts = Post.objects.all()
    print(hot_user)
    context = {
        "posts": posts,
        "my_mbti": my_mbti,
        "matched_user": matched_user,
        "hot_user": hot_user,
    }

    return render(request, "articles/main.html", context)


@login_required
def create(request):

    if request.method == "POST":
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            posts = post_form.save(commit=False)
            posts.park_address = Map.objects.get(pk=request.GET.get("park", ""))
            posts.user = request.user
            posts.save()
            return redirect("articles:board")
    else:
        post_form = PostForm()

    return render(request, "articles/create.html", {"post_form": post_form})


@login_required
def participate(request, pk):
    # article = get_object_or_404(Article, pk=pk)
    article = Post.objects.get(pk=pk)
    # 만약에 로그인한 유저가 이 글을 좋아요를 눌렀다면,
    # if article.like_users.filter(id=request.user.id).exists():
    if request.user in article.participate.all():
        # 참여하기 삭제하고
        article.participate.remove(request.user)
        is_participated = False
    else:
        # 참여하기 추가하고
        article.participate.add(request.user)
        is_participated = True

    data = {
        "isPart": is_participated,
        "partNumCount": article.participate.count(),
    }
    return JsonResponse(data)


# 취소
@login_required
def delete_participate(request, pk):
    post = Post.objects.get(pk=pk)
    post.participate.delete(request.user)
    return redirect("articles:detail", pk)


@login_required
def detail(request, pk):
    post = Post.objects.get(pk=pk)
    day = post.day
    comment_form = CommentForm()
    comments = Comment.objects.filter(post_id=post).order_by("-updated_at")
    post.hit += 1
    post.save()
    context = {
        "post": post,
        "comment_form": comment_form,
        "comments": comments,
        "day": day.strftime("%Y/%m/%d"),
        "name": post.park_address.parkNm,
        "latitude": post.park_address.latitude,
        "longitude": post.park_address.longitude,
    }

    return render(request, "articles/detail.html", context)


@login_required
def update(request, pk):
    posts = Post.objects.get(pk=pk)
    if request.user == posts.user:
        if request.method == "POST":
            post_form = PostForm(request.POST, instance=posts)
            if post_form.is_valid():
                post_form.save()
                return redirect("articles:detail", posts.pk)
        else:
            post_form = PostForm(instance=posts)

    return render(request, "articles/create.html", {"post_form": post_form})


@login_required
def delete(request, pk):
    posts = Post.objects.get(pk=pk)
    posts.delete()
    return redirect("articles:index")


@login_required
def comment(request, pk):
    post = Post.objects.get(pk=pk)
    post_pk = post.pk
    user = request.user.pk
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.post = post
        comment.user = request.user
        comment.save()

    temp = Comment.objects.filter(post_id=pk).order_by("-updated_at")
    comment_data = []

    for t in temp:
        t.updated_at = t.updated_at.strftime("%Y-%m-%d %H:%M")
        comment_data.append(
            {
                "user_id": t.user_id,
                "commentPk": t.pk,
                "content": t.content,
                "updated_at": t.updated_at,
                "profile_name": t.user.nickname,
                "profile_img": t.user.profile_pic.url,
            }
        )

    data = {
        "commentData": comment_data,
        "postPk": post_pk,
        "user": user,
    }
    return JsonResponse(data)


@login_required
def comment_delete(request, pk, comment_pk):
    post_pk = Post.objects.get(pk=pk).pk
    user = request.user.pk
    comment = Comment.objects.get(pk=comment_pk)

    if comment.user == request.user:
        comment.delete()

    temp = Comment.objects.filter(post_id=pk).order_by("-updated_at")
    comment_data = []

    for t in temp:
        t.updated_at = t.updated_at.strftime("%Y-%m-%d %H:%M")
        comment_data.append(
            {
                "user_id": t.user_id,
                "commentPk": t.pk,
                "content": t.content,
                "updated_at": t.updated_at,
                "profile_name": t.user.nickname,
                "profile_img": t.user.profile_pic.url,
            }
        )

    data = {
        "commentData": comment_data,
        "postPk": post_pk,
        "user": user,
    }
    return JsonResponse(data)


@login_required
def comment_update(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment_username = comment.user.username
    user = request.user.pk
    post_pk = Post.objects.get(pk=pk).pk
    jsonObject = json.loads(request.body)

    if request.method == "POST":
        comment.content = jsonObject.get("content")
        comment.save()

    temp = Comment.objects.filter(post_id=pk).order_by("-updated_at")
    comment_data = []

    for t in temp:
        t.updated_at = t.updated_at.strftime("%Y-%m-%d %H:%M")
        comment_data.append(
            {
                "user_id": t.user_id,
                "commentPk": t.pk,
                "content": t.content,
                "updated_at": t.updated_at,
                "profile_name": t.user.nickname,
                "profile_img": t.user.profile_pic.url,
            }
        )

    data = {
        "commentData": comment_data,
        "comment_pk": comment_pk,
        "comment_username": comment_username,
        "postPk": post_pk,
        "user": user,
    }
    return JsonResponse(data)


@login_required
def board(request):
    posts = Post.objects.all().order_by("-pk")
    page = request.GET.get("page")
    paginator = Paginator(posts, 10)
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        page = 1
        page_obj = paginator.page(page)
    except EmptyPage:
        page = paginator.num_pages
        page_obj = paginator.page(page)

    context = {
        "post": page_obj,
    }
    return render(request, "articles/board.html", context)


@login_required
def search(request):
    popular_list = {}
    if request.method == "GET":
        search = request.GET.get("searched", "")
        sort = request.GET.get("sorted", "")

        if not search.isdigit() and not search == "":
            # 검색받을 항목
            if Post.objects.filter(
                Q(title__icontains=search)
                | Q(content__icontains=search)
                | Q(day__icontains=search)
            ):
                popular_list[search] = popular_list.get(search, 0) + 1

        # 인기순
        for k, v in sorted(popular_list.items(), key=lambda x: -x[1]):
            if Search.objects.filter(title=k):
                s = Search.objects.get(title=k)
                s.count += 1
                s.save()
            else:
                s = Search(title=k, count=v)
                s.save()
        popular = Search.objects.order_by("-count")[:10]

        search_list = Post.objects.filter(
            Q(title__icontains=search)

articles/templates/articles/board.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %}
| 메이트찾기{% endblock title %}

{% block content %}
<section class='home'>
  <div class="inner-box">
    <h4>산책 메이트를 찾아보세요</h4>
    <a type="button" class="btn pos-btn" href="{% url 'map:map' %}">산책생성</a>
  </div>
</section>
<section class="container">
  <div class="board-box">
    <table class="sm-table align-middle">
      <thead>
        <tr>
          <th scope="col">제목</th>
          <th scope="col">산책날짜</th>
          <th scope="col">시간</th>
          <th scope="col">애완동물</th>
          <th scope="col">모집인원</th>
          <th scope="col">생성일</th>
          <th scope="col">조회수</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        {% for posts in post %}
        {% if posts.user not in request.user.blocking.all %}
        <tr>
          <td>
            <a href="{% url 'articles:detail' posts.pk %}">{{ posts.title }}</a>
          </td>
          <td>{{ posts.day|date:'Y년 m월 d일' }}</td>
          <td>{{ posts.time }}</td>
          <td>{% if posts.pet == 1 %}있어요{% else %}없어요{% endif %}</td>
          <td>{{ posts.participate.count}}/{{posts.participate_people}}</td>
          <td>{{ posts.created_at }}</td>
          <td>{{ posts.hit }}</td>
        </tr>
        {% else %}
        <tr><em class="text-secondary">차단한 유저의 게시글입니다.</em></tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- 페이징처리 시작 -->
  <ul class="pagination justify-content-center py-4">
    <!-- 이전페이지 -->
    {% if post.has_previous %}
      <li class="page-item d-flex flex-row">
        <a class="page-link" href="?page={{ post.previous_page_number }}"><i class="fa-solid fa-chevron-left"></i></a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-left"></i></a>
      </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in post.paginator.page_range %}
      {% if page_number >= post.number|add:-2 and page_number <= post.number|add:2 %}
        {% if page_number == post.number %}  
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if post.has_next %}
      <li class="page-item d-flex flex-row">
        <a class="page-link" href="?page={{ post.next_page_number }}"><i class="fa-solid fa-chevron-right"></i></a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-right"></i></a>
      </li>
    {% endif %}
  </ul>
  <!-- 페이징처리 끝 -->
</section>

{% comment %} <section class='container'>
  <div class="row">
    {% for posts in post %}{% if posts.user not in request.user.blocking.all %}
    <div class="col-3 mb-3">
      <div class="card rounded-3 shadow">
        <div class="badge bg-white text-black position-absolute" style="top: 0.5rem; right:0.5rem">
          👁‍🗨{{ posts.hit }}
        </div>
        {% if posts.thumbnail %}
        <img src="{{ posts.thumbnail.url }}" class="card-img-top " alt="...">
        {% else %}
        <img src="{% static 'images/base/article_base.jpg' %}" class="card-img-top">
        {% endif %}
        <div class="card-body">
          <h5 class="card-title">{{ posts.title }}</h5>
          <h5 class="card-title">{{ posts.park_address }}</h5>
          <a href="{% url 'articles:detail' posts.pk %}" class="pos-btn">자세히보기</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section> {% endcomment %}
{% endblock content %}

{% block script %}{% endblock script %}

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% block title %}{% endblock title %}

{% block content %}
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  {% if request.resolver_match.url_name == 'create' %}
    <div class="container ">
      <form class="p-4" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_title">Title</label>
          <input type="text" name="title" maxlength="50" class="form-control" placeholder="Title" required="" id="id_title">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_day">Day</label>
          <input type="date" name="day" class="form-control" placeholder="Day" required="" id="id_day">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_time">Time</label>
          <select name="time" class="form-select" required="" id="id_time">
            <option value="" selected="">---------</option>
            <option value="00:00">00:00</option>
            <option value="01:00">01:00</option>
            <option value="02:00">02:00</option>
            <option value="03:00">03:00</option>
            <option value="04:00">04:00</option>
            <option value="05:00">05:00</option>
            <option value="06:00">06:00</option>
            <option value="07:00">07:00</option>
            <option value="08:00">08:00</option>
            <option value="09:00">09:00</option>
            <option value="10:00">10:00</option>
            <option value="11:00">11:00</option>
            <option value="12:00">12:00</option>
            <option value="13:00">13:00</option>
            <option value="14:00">14:00</option>
            <option value="15:00">15:00</option>
            <option value="16:00">16:00</option>
            <option value="17:00">17:00</option>
            <option value="18:00">18:00</option>
            <option value="19:00">19:00</option>
            <option value="20:00">20:00</option>
            <option value="21:00">21:00</option>
            <option value="22:00">22:00</option>
            <option value="23:00">23:00</option>
            <option value="24:00">24:00</option>
          </select>
        </div>
        <div class="mb-3">
          <div class="form-check"><input type="checkbox" name="pet" class="form-check-input" id="id_pet">
            <label class="form-check-label" for="id_pet">애완동물 유/무</label>
          </div>
        </div>
        <div class="mb-3">
          <label class="form-label" for="participate_people">참여자</label>
          <input type="number" name="participate_people" class="form-control" value="2" required="" id="participate_people">
        </div>
        <div class="mb-3">
          <label class="form-label" for="thumbnail">Thumbnail</label>
          {% render_field form.thumbnail class="form-control" %}
        </div>
        <div class="mb-3">

          <label class="form-label" for="id_content">Content</label>
          <textarea name="content" cols="40" rows="10" class="form-control" placeholder="Content" required="" id="id_content"></textarea>
        </div>
        <input class="pos-btn" type="submit" value="글쓰기">
      </form>
    </div>
  {% else %}
    <!-- 수정하기 폼 -->
    <div class="container ">
      <form class="p-4" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_title">Title</label>
          <input type="text" name="title" maxlength="50" class="form-control" placeholder="{{post_form.title}}" required="" id="id_title">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_day">Day</label>
          <input type="date" name="day" class="form-control" placeholder="Day" required="" id="id_day">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_time">Time</label>
          <select name="time" class="form-select" required="" id="id_time">

            <option value="" selected="">---------</option>
            <option value="00:00">00:00</option>
            <option value="01:00">01:00</option>
            <option value="02:00">02:00</option>
            <option value="03:00">03:00</option>
            <option value="04:00">04:00</option>
            <option value="05:00">05:00</option>
            <option value="06:00">06:00</option>
            <option value="07:00">07:00</option>
            <option value="08:00">08:00</option>
            <option value="09:00">09:00</option>
            <option value="10:00">10:00</option>
            <option value="11:00">11:00</option>
            <option value="12:00">12:00</option>
            <option value="13:00">13:00</option>
            <option value="14:00">14:00</option>
            <option value="15:00">15:00</option>
            <option value="16:00">16:00</option>
            <option value="17:00">17:00</option>
            <option value="18:00">18:00</option>
            <option value="19:00">19:00</option>
            <option value="20:00">20:00</option>
            <option value="21:00">21:00</option>
            <option value="22:00">22:00</option>
            <option value="23:00">23:00</option>
            <option value="24:00">24:00</option>
          </select>
        </div>
        <div class="mb-3">
          <div class="form-check"><input type="checkbox" name="pet" class="form-check-input" id="id_pet">
            <label class="form-check-label" for="id_pet">애완동물 유/무</label>
          </div>
        </div>
        <div class="mb-3">
          <label class="form-label" for="participate_people">참여자</label>
          <input type="number" name="participate_people" class="form-control" placeholder="{{post_form.participate_people}}" required="" id="participate_people">
        </div>
        <div class="mb-3">

          <label class="form-label" for="id_content">Content</label>
          <textarea name="content" cols="40" rows="10" class="form-control" placeholder="{{post_form.content}}" required="" id="id_content"></textarea>
        </div>
        <input class="pos-btn" type="submit" value="글수정">
      </form>
    </div>
  {% endif %}
{% endblock content %}
{% block script %}{% endblock script %}

articles/templates/articles/index.html
{% extends 'nonav_base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}

{% block title %}{% endblock title %}

{% block section %}
  <section class="start-container">
    {% if request.user.is_authenticated %}
      <a href="{% url 'articles:main' %}" class="start-btn glass">ENTER</a>
    {% else %}
      <a href="{% url 'accounts:login' %}" class="start-btn glass">ENTER</a>
    {% endif %}
  </section>
{% endblock section %}

{% block script %}{% endblock script %}

articles/templates/articles/main.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
{% load embed_video_tags %}

{% block title %}
  | 홈{% endblock title %}

{% block style %}{% endblock style %}

{% block content %}
  <section class="home">
    <div class="inner-box">
      <h3>🔎 메이트 찾아보기</h3>
      <form action="{%url 'articles:search' %}" class="search d-flex" role="search" method="">
        <input type="text" style="display:none">
        <input type="password" style="display:none">
        <input class="form-control me-2" name="searched" type="search" placeholder="키워드를 입력해주세요." aria-label="Search">
        <button class="btn pos-btn" type="submit">검색</button>
      </form>
    </div>
  </section>
  <section class='container'>
    <div class="recommended">
      <div class="mt-3 mb-5">
        <h3>#<b>{{ user.mbti }}</b>
          인 당신을 위한 산책 메이트</h3>
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-1 row-cols-xs-1 gx-4">
          {% if matched_user %}
            {% for user_info in matched_user %}
              <div class="col mb-5">
                <div class="card h-100">
                  <img class="card-img-top" src="{{ user_info.get_photo_url }}" alt="프사"/>
                  <div class="card-body py-4">
                    <h5 class="fw-bold text-center">{{ user_info.nickname }}</h5>
                  </div>
                  <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
                    <a class="btn btn-outline-dark text-center" href="{% url 'accounts:detail' user_info.pk %}">자세히보기</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <div class="none-box">추천 유저가 없어요<i class="fa-regular fa-face-frown"></i>
            </div>
          {% endif %}
        </div>
      </div>
      <div class="mt-3 mb-3">
        <h3>#Manner Stack Overflow! 산책매너 좋은 유저</h3>
        <div class="row row-cols-lg-3 row-cols-md-2 row-cols-sm-1 row-cols-xs-1 gx-4">
          {% if hot_user %}
            {% for hot_info in hot_user %}
              <div class="col mb-5">
                <div class="card h-100">
                  <img class="card-img-top" src="{{ hot_info.get_photo_url }}" alt="프사"/>
                  <div class="card-body py-4">
                    <h5 class="fw-bold text-center">{{ hot_info.nickname }}</h5>
                  </div>
                  <div class="card-footer bg-light p-4 pt-0 border-top-0 bg-transparent">
                    <a class="btn pos-btn text-center" href="{% url 'accounts:detail' hot_info.pk %}">자세히보기</a>
                  </div>
                </div>
              </div>
            {% endfor %}
          {% else %}
            <div class="none-box">추천 유저가 없어요<i class="fa-regular fa-face-frown"></i>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
    <!--recommended-->
  </section>
{% endblock content %}
{% block script %}{% endblock script %}

articles/templates/articles/searchfail.html
{% extends 'base.html' %}

{% block content %}
  <div style="height:100px"></div>
  <div class="container mt-5 mb-3">
    <div class="search-box">
      <form action="{%url 'articles:search' %}" class="search d-flex" role="search" method="">
        <input type="text" style="display:none" autocomplete="off">
        <input type="password" style="display:none" autocomplete="off">
        <input class="form-control me-2" name="searched" type="search" placeholder="Search" aria-label="Search" autocomplete="off">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

  <div class="container d-flex justify-content-center">
    <h1>{{v}}</h1>
  </div>
{% endblock %}