accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("detail/<int:pk>/", views.detail, name="detail"),
    path("update/<int:pk>/", views.update, name="update"),
    path("<int:pk>/follow/", views.follow, name="follow"),
    path("logout/", views.logout, name="logout"),
    path("delete/", views.delete, name="delete"),
    path("<int:pk>/block", views.block, name="block"),
    path("block_user/", views.block_user, name="block_user"),
    path("<int:pk>/block_user_block", views.block_user_block, name="block_user_block"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("main/", views.main, name="main"),
    path("board/", views.board, name="board"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="delete"),

    path("<int:pk>/delete_participate/", views.delete_participate, name="delete_participate"),

    path("<int:pk>/comment/", views.comment, name="comment"),
    path(
        "<int:pk>/comment_delete/<int:comment_pk>",
        views.comment_delete,
        name="comment_delete",
    ),
    path(
        "<int:pk>/comment_update/<int:comment_pk>",
        views.comment_update,
        name="comment_update",
    ),
    path("<int:pk>/participate/", views.participate, name="participate"),
    path("search/", views.search, name="search"),
    path("searchfail/", views.searchfail, name="searchfail"),
    path("support/", views.support, name="support"),
]

maps/urls.py
from django.urls import path
from . import views

app_name = "map"

urlpatterns = [
    path("map/", views.map, name="map"),
    path("map/<str:x>/<str:y>/", views.map_search, name="map_search"),
    path("map/search/<str:x>/<str:y>/", views.search, name="search"),
]

sanmepjt/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("articles.urls")),
    path("map/", include("maps.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">

  <head>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/base/chat.ico' %}">
    <title>산책메이트
      {% block title %}{% endblock title %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block style %}{% endblock style %}
  </head>

  <body data-spy="scroll" data-target="#scroll-spy">
    <header>
      <!-- place navbar here -->
      <nav class="nav">
        <div class="container">
          <div class="logo">
            {% if request.user.is_authenticated %}
              <a href="{% url 'articles:main' %}"><img src="{% static 'images/base/navlogo.png' %}" height="60px" alt="네브로고"></a>
            {% else %}
              <a href="{% url 'articles:index' %}"><img src="{% static 'images/base/navlogo.png' %}" height="60px" alt="네브로고"></a>
            {% endif %}
          </div>
          <div id="mainListDiv" class="main_list">
            <ul class="navlinks">
              <li>
                <a href="{% url 'map:map' %}">공원찾기</a>
              </li>
              <li>
                <a href="{% url 'articles:board' %}">산책해요</a>
              </li>
              <li class="pf_list">
                <a href="{% url 'articles:support' %}">고객지원</a>
              </li>
              {% if request.user.is_authenticated %}
                <li class="dd-toggle">
                  <a class="dd-btn" aria-hidden="true">
                    {{ user.nickname }}
                    님
                    <i class="bi bi-caret-down-fill"></i>
                  </a>
                  <ul class="arrow_box">
                    <li class="dd-list">
                      <a class="dd-item" href="{% url 'accounts:detail' user.pk %}">
                        <i class="bi bi-person-fill"></i>
                        내 정보</a>
                    </li>
                    <li class="dd-list">
                      <a class="dd-item" href="{% url 'accounts:update' user.pk %}">
                        <i class="bi bi-pencil-square"></i>
                        정보 수정</a>
                    </li>
                    <li class="dd-list">
                      <a class="dd-item" href="{% url 'accounts:logout' %}">
                        <i class="bi bi-box-arrow-right"></i>
                        로그아웃</a>
                    </li>
                  </ul>
                </li>
              {% endif %}
            </ul>
          </div>
          <span class="navTrigger">
            <i></i>
            <i></i>
            <i></i>
          </span>
        </div>
        <span class="navTrigger">
          <i></i>
          <i></i>
          <i></i>
        </span>
      </nav>
      <!-- /.fixed navigation -->
    </header>
    <main>
      {% block content %}{% endblock content %}
    </main>
    <footer>
      <!-- place footer here -->
      <span class="me-5">@2022 SANME 간정진 김다솔 신우철 이제준 최준혁</span>
      <img src="{% static 'images/base/navlogo.png' %}" alt="footerlogo">
    </footer>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <!-- Jquery needed -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Function used to shrink nav bar removing paddings and adding black background -->
    <script>
      // nav scroll
      $(window).scroll(function () {
        if ($(document).scrollTop() > 50) {
          $('.nav').addClass('affix');
          console.log("OK");
        } else {
          $('.nav').removeClass('affix');
        }
      });

      $('.navTrigger').click(function () {
        $(this).toggleClass('active');
        console.log("Clicked menu");
        $("#mainListDiv").toggleClass("show_list");
        $("#mainListDiv").fadeIn();

      });
    </script>
    {% block script %}{% endblock script %}
  </body>

</html>

templates/nonav_base.html
{% load static %}
{% load widget_tweaks %}
{% load django_bootstrap5 %}
<!doctype html>
<html lang="en">

  <head>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/base/chat.ico' %}">
    <title>산책메이트
      {% block title %}{% endblock title %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block style %}{% endblock style %}
  </head>

  <body>
    <main class="index-home">
      <div class="triangle"></div>
      <p class="Ptop">혼자 말고🙅‍♂️ 친구 아닌👩‍❤️‍👨</p>
      <img src="{% static 'images/base/logo.png' %}" alt="indexlogo">
      <p class="Pbottom">지금 시작하세요</p>
      <!--로그인폼 위 설명-->
      {% block section %}{% endblock section %}
    </main>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    {% block script %}{% endblock script %}
  </body>

</html>